### PR TITLE
fix(buttonwithdialog): extends closeonblur condition with focus handler

### PR DESCRIPTION
**Pull request by congcongcong250**
This change is [Reviewable](https://reviewable.io/reviews/qantasairways/runway/143)

### CODE REVIEW

**Comment by jamesb3ll** [comment]
Looks good to me!

**Comment by congcongcong250** [comment]
Potential issue: click on an outside input could cause handler to be triggered twice

**Comment by tysonwolker** [comment]
Prefer rebase over having merge commits in the branch.

**Comment by jamesb3ll** [comment]
Does this PR make sense anymore with wanting in the future to keep the focus inside modals (including inline modals) when they are open?

**Comment by congcongcong250** [comment]
Closed due to conflict of functionality against #162

**Pull request closed without merging**
